
export const OPENLOGIN = 'OPENLOGIN';
export const CLOSELOGIN = 'CLOSELOGIN';
export const LOGININPUTERROR = 'LOGININPUTERROR';
export const LOGOUT = 'LOGOUT';//退出登录

export const ACCESSSUCCESS = 'ACCESSSUCCESS';

export const SHOWSNACKBAR = 'SHOWSNACKBAR';
export const HIDESNACKBAR = 'HIDESNACKBAR';

export const SHOWPROGRESS = 'SHOWPROGRESS';
export const HIDEPROGRESS = 'HIDEPROGRESS';

export const SHOWPROFILE = 'SHOWPROFILE';
export const HIDEPROFILE = 'HIDEPROFILE';

export const FETCHTOPICSUCCESS = 'FETCHTOPICSUCCESS';

export const PAGECHANGE = 'PAGECHANGE';

export const ADDTOPICSUCCESS = 'ADDTOPICSUCCESS';

export const COLLECTSUCCESS = 'COLLECTSUCCESS';//收藏成功

export const DECOLLECTSUCCESS = 'DECOLLECTSUCCESS';//取消收藏成功

export const GETMESSAGECOUNTSUCCESS = 'GETMESSAGECOUNTSUCCESS';//获取未读数

export const GETUSERMESSAGESUCCESS = 'GETUSERMESSAGESUCCESS';//获取用户消息