const INFO_LOGIN_SUCCESS = '登录成功';
const INFO_LOGIN_FAIL = '登录失败';
const INFO_FETCH_TOPIC_SUCCESS = '刷新帖子列表成功';
const INFO_FETCH_TOPIC_FAIL = '刷新帖子列表失败';
const INFO_ADD_TOPIC_SUCCESS = '发帖成功';
const INFO_ADD_REPLY_SUCCESS = '回复成功';
const INFO_MARK_TOPIC_SUCCESS = '收藏成功';

export default {
	INFO_LOGIN_SUCCESS,
	INFO_LOGIN_FAIL,
	INFO_FETCH_TOPIC_SUCCESS,
	INFO_FETCH_TOPIC_FAIL,
	INFO_ADD_TOPIC_SUCCESS,
	INFO_ADD_REPLY_SUCCESS,
	INFO_MARK_TOPIC_SUCCESS
}